version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      commit-message:
          prefix: "chore"
      cooldown:
          default-days: 1
          include:
              - "*"
